{% set name = "drux" %}
{% set version = "0.1" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/openscilab/drux
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - setuptools
        - python >=3.7
    run:
        - python >=3.7
        - numpy >=1.19.0
        - matplotlib >=3.2.2
about:
    home: https://github.com/openscilab/drux
    license: MIT
    license_family: MIT
    summary: Drux: Drug Release Analysis Framework
    description: |
        Drux is a Python-based framework for simulating drug release profiles using mathematical models.
        It offers a reproducible and extensible platform to model, analyze, and visualize time-dependent drug release behavior, making it ideal for pharmaceutical research and development.
        By combining simplicity with scientific rigor, Drux provides a robust foundation for quantitative analysis of drug delivery kinetics.
	
        Website: https://openscilab.com

        Repo: https://github.com/openscilab/drux
extra:
    recipe-maintainers:
        - alirezazolanvari
        - sepandhaghighi
